[env]
TERM = "xterm-256color"

[window.padding]
x = 3
y = 3

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false 
thickness = 0.6

[cursor.style]
shape = "Underline"
blinking = "Always"
